config/routes.rb
Tsc003::Application.routes.draw do
  
  resources :news_items


  get "news/index"

  get "sitemaps/show"

  get "about/index", :id => "about"
  match "about" => "about#index"

  # get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
  resources :sitemaps, :only => :show
  match "/sitemap.xml", :controller => "sitemaps", :action => "show", :format => :xml

  resources :contact_forms


  get "terms/index", :id => "terms"
  match "terms" => "terms#index"

  get "privacy/index", :id => "privacy"
  match "privacy" => "privacy#index"

  get "startup_maps/index", :id => "startup_maps"
  match "startup_maps" => "startup_maps#index"

  match 'tagged' => 'user_profiles#tagged', :as => 'tagged'

  get "start/index", :id => "start"
  match "start" => "start#index"

  
  resources :business_profiles do
    member do
      post :join
      post :leave
      post :remove
    end
  end

  resources :profile_types

  get "admin/index", :id => "admin"
  match "admin" => "admin#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :user_profiles
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    
    end
    can :edit, UserProfile, :user_id => user.id
    can :edit, BusinessProfile, :owner => user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
  acts_as_gmappable #:check_process => false
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :address, :description, :email, :employees, :facebook, :google, :hiring,
   :image, :name, :phone, :slug, :twitter, :url, :profile_type_ids, :specialty_list, :responsible

  validates_presence_of :description
  validates_uniqueness_of :slug

  has_many :business_profile_types
  has_many :profile_types, :through => :business_profile_types
  has_many :user_business_profiles
  has_many :users, :through => :user_business_profiles

  def gmaps4rails_address
    "#{self.address}" 
  end

  def gmaps4rails_infowindow
    "<a href=\"#{url}\" target=\"_blank\"><h4>#{name}</h4></a>" << "<h4>#{address}</h4>" << "<h4>#{email}</h4>"
  end

  def belongs?(user)
    self.users.first == user.id
  end  

  def find_tag(profile_type_id)
    BusinessProfile.joins(:profile_types).where(:profile_type => {:profile_type_id => profile_type_id})
  end

  default_scope order: 'business_profiles.created_at DESC'

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  attr_accessible :content, :email, :name, :phone, :subject
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :flagged, :title, :url, :votes
end

app/models/profile_type.rb
class ProfileType < ActiveRecord::Base
  attr_accessible :name

  has_many :business_profile_types
  has_many :business_profiles, :through => :business_profile_types

  default_scope order: 'profile_types.name ASC'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged


  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :user_profile_id, :slug, :opt_in

  validates_uniqueness_of :slug
  validates_acceptance_of :accept_terms

  has_one :user_profile, :dependent => :destroy
  has_many :user_business_profiles
  has_many :business_profiles, :through => :user_business_profiles

  def works_here?(business_profile)
    self.business_profiles.include?(business_profile)
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  belongs_to :user

  attr_accessible :about, :email, :facebook, :google, :image, :mentor, :phone, :slug,
   :twitter, :url, :tagline, :linkedin, :github, :skill_list, :interest_list

  validates_presence_of :about, :tagline

  default_scope order: 'user_profiles.created_at DESC'

  def get_user_name
    self.user.try :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_for_mobile
  def index
    @business_profiles = BusinessProfile.limit(5)
    @user_profiles = UserProfile.limit(5)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/admin/_business_profiles.html.erb
<h2>Business profiles</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th></th>
    <th></th>
  </tr>

<% @business_profiles.each do |bp| %>
  <tr>
    <td><%= link_to bp.name, business_profile_path(bp) %></td>
    <td><%= bp.users.first.try :name %></td>
    <td><%= link_to 'Edit', edit_business_profile_path(bp) %></td>
    <td><%= link_to 'Delete', bp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

app/views/admin/_profile_types.html.erb
<h2>Business profile types</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @profile_types.each do |profile_type| %>
  <tr>
    <td><%= profile_type.name %></td>
    <td><%= link_to 'Edit', edit_profile_type_path(profile_type) %></td>
    <td><%= link_to 'Delete', profile_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Profile type', new_profile_type_path, :class => "btn btn-success" %>

app/views/admin/_users.html.erb
<h2>Users</h2>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Opt in</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.opt_in %>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<div class="row">
  <div class="span12">
    <h1>TSC admin panel</h1>
  </div>
</div>
<div class="row">
  <div class="span12">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#blog" data-toggle="tab">Business Profiles</a></li>
      <li><a href="#applications" data-toggle="tab">Profile Types</a></li>
      <li><a href="#users" data-toggle="tab">Users</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="blog">
        <%= render 'business_profiles' %>
      </div>
      <div class="tab-pane" id="applications">
        <%= render 'profile_types' %>
      </div>
      <div class="tab-pane" id="users">
        <%= render 'users' %>
      </div>
             
    </div>
  </div>
</div>
              

              

              