config/routes.rb
Tsc003::Application.routes.draw do
  
  resources :news_items


  get "news/index"

  get "sitemaps/show"

  get "about/index", :id => "about"
  match "about" => "about#index"

  # get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
  resources :sitemaps, :only => :show
  match "/sitemap.xml", :controller => "sitemaps", :action => "show", :format => :xml

  resources :contact_forms


  get "terms/index", :id => "terms"
  match "terms" => "terms#index"

  get "privacy/index", :id => "privacy"
  match "privacy" => "privacy#index"

  get "startup_maps/index", :id => "startup_maps"
  match "startup_maps" => "startup_maps#index"

  match 'tagged' => 'user_profiles#tagged', :as => 'tagged'

  get "start/index", :id => "start"
  match "start" => "start#index"

  
  resources :business_profiles do
    member do
      post :join
      post :leave
      post :remove
    end
  end

  resources :profile_types

  get "admin/index", :id => "admin"
  match "admin" => "admin#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :user_profiles
end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
  acts_as_gmappable #:check_process => false
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :address, :description, :email, :employees, :facebook, :google, :hiring,
   :image, :name, :phone, :slug, :twitter, :url, :profile_type_ids, :specialty_list, :responsible

  validates_presence_of :description
  validates_uniqueness_of :slug

  has_many :business_profile_types
  has_many :profile_types, :through => :business_profile_types
  has_many :user_business_profiles
  has_many :users, :through => :user_business_profiles

  def gmaps4rails_address
    "#{self.address}" 
  end

  def gmaps4rails_infowindow
    "<a href=\"#{url}\" target=\"_blank\"><h4>#{name}</h4></a>" << "<h4>#{address}</h4>" << "<h4>#{email}</h4>"
  end

  def belongs?(user)
    self.users.first == user.id
  end  

  def find_tag(profile_type_id)
    BusinessProfile.joins(:profile_types).where(:profile_type => {:profile_type_id => profile_type_id})
  end

  default_scope order: 'business_profiles.created_at DESC'

end

app/models/business_profile_type.rb
class BusinessProfileType < ActiveRecord::Base
  belongs_to :business_profile
  belongs_to :profile_type
  # attr_accessible :title, :body
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :check_for_mobile

  def join
    @business_profile = BusinessProfile.find(params[:id])
    @user = current_user

    if not @user.works_here?(@business_profile)
      @business_profile.users << @user
      flash[:notice] = 'You have been added to this business'
    else
      flash[:error] = 'You are already associated with this business_profile'
    end
    redirect_to @business_profile
  end

  def leave
    @business_profile = BusinessProfile.find(params[:id])
    @user = current_user

    if @user.works_here?(@business_profile)
      @user.business_profiles.delete(@business_profile)
      flash[:notice] = 'You have been removed from this business'

    else
      flash[:error] = 'You are not associated with this business_profile'
    end
    redirect_to @business_profile
  end

  def remove
    @business_profile = BusinessProfile.find(params[:id])
    @user = User.find(params[:user])

    if current_user.id == @business_profile.owner
      @user.business_profiles.delete(@business_profile)
      flash[:notice] = "You have removed the user from your business profile"
    else
      flash[:error] = "You are not authorised to remove the user"
    end
    redirect_to @business_profile
  end

  # GET /business_profiles
  # GET /business_profiles.json
  def index
    @profile_types = ProfileType.all
    @tag = params[:tag]
    if params[:tag].present?
      tag_value = params[:tag]
      @business_profiles = BusinessProfile.joins(:business_profile_types).where(:business_profile_types => {:profile_type_id => tag_value})
    else
      @business_profiles = BusinessProfile.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_profiles }
    end
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @business_profile = BusinessProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business_profile }
    end
  end

  # GET /business_profiles/new
  # GET /business_profiles/new.json
  def new
    @business_profile = BusinessProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business_profile }
    end
  end

  # GET /business_profiles/1/edit
  def edit
    @business_profile = BusinessProfile.find(params[:id])
    authorize! :edit, @business_profile
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(params[:business_profile])
    @business_profile.users << current_user
    @business_profile.owner = current_user.id
    
    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render json: @business_profile, status: :created, location: @business_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /business_profiles/1
  # PUT /business_profiles/1.json
  def update
    @business_profile = BusinessProfile.find(params[:id])
    
    respond_to do |format|
      if @business_profile.update_attributes(params[:business_profile])
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile = BusinessProfile.find(params[:id])
    @business_profile.destroy

    respond_to do |format|
      format.html { redirect_to business_profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/business_profiles_helper.rb
module BusinessProfilesHelper
  def get_name
    "Check out " + @business_profile.name + "'s profile " + @business_profile.twitter
  end

  def profile_type_with_count(profile_type)
    profile_type.name + " (" + profile_type.business_profiles.count.to_s + ")"
  end
end

app/views/business_profiles/_about.html.erb
<%= image_tag(@business_profile.image_url,:class => "user-pic") %>
    <p>
      <% @business_profile.profile_types.each_with_index do |profile_type, index| %>
        <%= profile_type.name %> <% if index < @business_profile.profile_types.count - 1 %> | <% end %>
      <% end %>
    </p>
    <p>
      <b>About:</b><br />
      <%= @business_profile.description %>
    </p>
    <p>
      <b>Hiring?</b> 
      <% if @business_profile.hiring %>Yes<% else %>No<% end %>
    </p>
    
    <h3>People</h3>
    
    <% @business_profile.users.each do |user| %>
      <% if user.user_profile %>
        <p><%= image_tag user.user_profile.image_url,:class => "profile-pic" if user.user_profile.image_url %>
        <b><%= link_to user.name, user_profile_path(user.user_profile) %></b></p>
        <% if user_signed_in? && @business_profile.owner == current_user.id && current_user != user %>
          <%= link_to "This user does not work here", remove_business_profile_path(:user => user), :method => :post, :class => "btn" %>
        <% end %>
      <% end %>
    <% end %>
    
    <% if !user_signed_in? %>
      <p>Do you work here?</p> 
      <p><%= link_to 'Log in', new_user_session_path %> and create a user profile to be added to this page.</p>
    <% end %>
    <% if user_signed_in? && !current_user.user_profile %>
    <p>Do you work here?</p> 
      <%= link_to 'Create a user profile', new_user_profile_path %> to be added to this page.</p>
    <% end %>
    <% if user_signed_in? && !current_user.works_here?(@business_profile) && @business_profile.owner != current_user.id && current_user.user_profile %>
      <p></p>
      <p><%= link_to 'I work here', join_business_profile_path, :method => :post, :class => 'btn' %></p>
    <% end %>

    


    <% if user_signed_in? && current_user.works_here?(@business_profile) && @business_profile.owner != current_user.id %>
      <p><%= link_to 'I no longer work here', leave_business_profile_path, :method => :post, :class => 'btn' %></p>
    <% end %>

app/views/business_profiles/_business_list.html.erb
<br />
    <table class="table">
      <tr>
        <th width="10%"></th>
        <th width="25%">Name</th>
        <th width="40%">Description</th>
        <th>Business type</th>
        </tr>   

    <% @business_profiles.each do |business_profile| %>

      <tr>
        <td><%= image_tag(business_profile.image_url, :class => "profile-pic") %></td>
        <td><strong><%= link_to business_profile.name, business_profile_path(business_profile) %></strong></td>
        <td><%= business_profile.description[0..200] %></td>
        <td>
          <% business_profile.profile_types.each do |pt| %>
            <%= link_to pt.name, business_profiles_url(:tag => pt) %><br />
          <% end %>
        </td>      </tr>

    <% end %>
  </table>

app/views/business_profiles/_contact.html.erb
<h2>Contact info</h2>
<table class="table">
      <% if @business_profile.address.to_s != '' %>
        <tr>
          <th width="50px"> &nbsp;<i class="icon-map-marker icon-2x"></i> </th>
          <td><a href="http://maps.google.com/maps?q=<%= @business_profile.address %>"><%= @business_profile.address %></a></td>
        </tr>
      <% end %>
      <% if @business_profile.email.to_s != '' %>
        <tr>
          <th width="50px"><i class="icon-envelope-alt icon-2x"></i> </th>
          <td><a href="mailto:'<%= @business_profile.email %>'"><%= @business_profile.email %></a></td>
        </tr>
      <% end %>
      <% if @business_profile.phone.to_s != '' %>
        <tr>
          <th>&nbsp;&nbsp;<i class="icon-mobile-phone icon-2x"></i></th>
          <td><a href="tel:'<%= @business_profile.phone %>'"><%= @business_profile.phone %></a></td>
        </tr>
      <% end %>
      <% if @business_profile.url.to_s != '' %>
        <tr>
          <th><i class="icon-laptop icon-2x"></i></th>
          <td><a href='<%= @business_profile.url.to_s %>' target="_blank"><%= @business_profile.url.to_s %></a></td>
        </tr>      
      <% end %>
      <% if @business_profile.twitter.to_s != '' %>
        <tr>
          <th><i class="icon-twitter icon-2x"></i></th>
          <td><a href='http://twitter.com/<%= @business_profile.twitter.to_s %>' target="_blank"><%= @business_profile.twitter %></a></td>
        </tr>
      <% end %>
      <% if @business_profile.facebook.to_s != '' %>
        <tr>
          <th>&nbsp;<i class="icon-facebook icon-2x"></i></th>
          <td>
            
              <a href='<%= @business_profile.facebook.to_s %>' target="_blank">Facebook profile</a>
          </td>
        </tr>
      <% end %>
      <% if @business_profile.google.to_s != '' %>
        <tr>
          <th><i class="icon-google-plus icon-2x"></i></th>
          <td>
              <a href='<%= @business_profile.google.to_s %>' target="_blank">Google+ page</a>
            </td>
        </tr>
      <% end %>
      <% if @business_profile.linkedin.to_s != '' %>
        <tr>
          <th><i class="icon-linkedin icon-2x"></i></th>
          <td>
              <a href='<%= @business_profile.linkedin.to_s %>' target="_blank">LinkedIn profile</a>
          </td>
        </tr>
      <% end %>
      <% if @business_profile.github.to_s != '' %>
        <tr>
          <th><i class="icon-github-alt icon-2x"></i></th>
          <td>
              <a href='<%= @business_profile.github.to_s %>' target="_blank">Github profile</a>
          </td>
        </tr>
      <% end %>

    </table>
    <% if user_signed_in? %>
      <% if @business_profile.owner == current_user.id %>
        <%= link_to 'Edit', edit_business_profile_path(@business_profile), :class=> "btn btn-warning" %>
        <%= link_to 'Delete', @business_profile, method: :delete, data: { confirm: 'Are you sure you want to delete this profile?' }, :class=> "btn btn-danger" %>
      <% end %>
    <% end %>

app/views/business_profiles/_edit_form.html.erb
<%= simple_form_for @business_profile, :html => {:multipart => true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile_types, :as => :check_boxes, :label => 'Select your business type', :required => true %>
    <%= f.input :name, :label => 'Business name' %>
    <%= f.input :address, :required => true, :label => 'Business address', :placeholder => 'Street address, suburb, postcode' %>
    <%= f.input :email, :label => 'Email' %>
    <%= f.input :phone, :label => 'Phone' %>
    <%= f.input :description, :label => 'Description', :input_html => { :rows => 5, :class => "span7" }, :required => true %>
    <%= f.input :url, :label => 'Business website URL', :placeholder => "http://www.my-business.com" %>
    <%= f.input :twitter, :label => 'Twitter account', :placeholder => '@handle' %>
    <%= f.input :facebook, :label => 'Facebook page', :placeholder => "https://facebook.com/your-business-name" %>
    <%= f.input :google, :label => 'Google+ page', :placeholder => 'https://plus.google.com/xxxxx' %>
    <%= f.input :employees, :label => 'No. of employees', :collection => ['1', '2-5', '6-10', '11-20', '21-50', '50+'] %>
    <%= f.input :hiring, :label => 'Are you currently hiring?' %>
    <p>Current logo<br /><%= image_tag @business_profile.image_url,:class => "profile-pic" if @business_profile.image_url %></p>
    <%= f.input :image, :as => :file, :label => "Change Logo" %>
  </div>

  
    <%= f.submit 'Update your business', :class => "btn btn-success" %>
<%= link_to 'Cancel', business_profiles_path %>
  
<% end %>

app/views/business_profiles/_filter_list.html.erb
<h3>View by type</h3>
      <% if @profile_types %>
        
        <% @profile_types.each do |profile_type| %>
        <% if profile_type.id == @tag.to_i %>
        <p>
          <%= link_to profile_type_with_count(profile_type), business_profiles_url(:tag => profile_type), :class => "btn btn-primary btn-fixed-width-3" %>
        </p>
        <% else %>
        <p>
          <%= link_to profile_type_with_count(profile_type), business_profiles_url(:tag => profile_type), :class => "btn btn-info btn-fixed-width-3" %>
        </p>
        <% end %>
      <% end %>
    <% end %>
      <p>
        <%= link_to 'Clear filter', business_profiles_url, :class => "btn btn-warning btn-fixed-width-3" %>
      </p>

app/views/business_profiles/_form.html.erb
<%= simple_form_for @business_profile, :html => {:multipart => true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile_types, :as => :check_boxes, :label => 'Select your business type', :required => true %>
    <%= f.input :name, :label => 'Business name' %>
    <%= f.input :address, :required => true, :label => 'Business address', :placeholder => 'Street address, suburb, postcode' %>
    <%= f.input :email, :label => 'Email', :placeholder => "user@example.com" %>
    <%= f.input :phone, :label => 'Phone' %>
    <%= f.input :description, :label => 'Description', :input_html => { :rows => 5, :class => "span7" }, :required => true %>
    <%= f.input :url, :label => 'Business website URL', :placeholder => "http://www.my-business.com" %>
    <%= f.input :twitter, :label => 'Twitter account', :placeholder => '@handle' %>
    <%= f.input :facebook, :label => 'Facebook page', :placeholder => "https://facebook.com/your-business-name" %>
    <%= f.input :google, :label => 'Google+ page', :placeholder => 'https://plus.google.com/xxxxx' %>
    <%= f.input :employees, :label => 'No. of employees', :collection => ['1', '2-5', '6-10', '11-20', '21-50', '50+'] %>
    <%= f.input :hiring, :label => 'Are you currently hiring?' %>

    <%= f.input :image, :as => :file, :label => "Logo" %>
    <p>* By clicking the 'Add your business' button I understand that I will be set as the admininstrator for my business profile.</p>
  </div>

  
    <%= f.submit 'Add your business', :class => "btn btn-success", :title => 'You must agree to be adminstrator to register your business.' %>
  
<% end %>

app/views/business_profiles/_index_title.html.erb
<% content_for :title, "Startups - Sydney - The Startup Community. List your startup and yourself - get connected!" %>
<% content_for :description, "The Startup Community - Sydney: List of startups and businesses servicing startups in the Sydney area." %>

app/views/business_profiles/_share.html.erb
<h2>Share</h2>
<p>Tweet about this profile</p>
<%= link_to 'Tweet', "https://twitter.com/share", :class => "twitter-share-button", :data => { :text => get_name, :via => "SydSUCommunity", :size => "large" } %><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<br>
<% if @business_profile.facebook %>
<p>Recommend on Facebook</p>
  <div class="fb-like" data-href="<%= @business_profile.facebook %>" data-send="false" data-layout="button_count" data-width="200" data-show-faces="true" data-action="recommend"></div>
<br>
<% end %>

<p>Share on LinkedIn</p>

<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/Share" data-counter="right"></script>

app/views/business_profiles/edit.html.erb
<h1>Edit your business profile</h1>

<%= render 'edit_form' %>

app/views/business_profiles/index.html.erb
<%= render 'index_title' %>

<div class="row">
  <div class ="span9">
    <h1><i class="icon-building"></i> Business Profiles <span style="font-size:20px">(<%= @business_profiles.count.to_s %>)</span></h1>
    <br />
  </div>
  <div class="span3">
    <br>
    <p><%= link_to "Create your business profile", new_business_profile_path, :class => "btn btn-success" %></p>
  </div>
</div>
<div class="row">
  <div class="span3">
    <%= render 'filter_list' %>
  </div>

  <div class="span9">
    <%= render 'business_list' %>
  </div>
</div>

app/views/business_profiles/new.html.erb
<h1>Create a business profile</h1>

<%= render 'form' %>

<%= link_to 'Cancel', business_profiles_path %>

app/views/business_profiles/show.html.erb
<% content_for :title, @business_profile.name + " The Startup Community - Sydney. List yourself and your startup - get connected!" %>
<% content_for :description, @business_profile.name + @business_profile.description %>
<%= render 'layouts/facebook_script' %>

<div class="row">
  <div class ="span12">
    <h1><%= @business_profile.name %></h1>
    <br />
  </div>
</div>

<div class="row">
  <div class="span3">
    <%= render 'about' %>
    
  </div>

  <div class="span5">
    <%= render 'contact' %>
    
    
  </div>
  <div class="span4">
    <%= render 'share' %>
  </div>
</div>