config/routes.rb
Tsc003::Application.routes.draw do
  
  resources :news_items


  get "news/index"

  get "sitemaps/show"

  get "about/index", :id => "about"
  match "about" => "about#index"

  # get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
  resources :sitemaps, :only => :show
  match "/sitemap.xml", :controller => "sitemaps", :action => "show", :format => :xml

  resources :contact_forms


  get "terms/index", :id => "terms"
  match "terms" => "terms#index"

  get "privacy/index", :id => "privacy"
  match "privacy" => "privacy#index"

  get "startup_maps/index", :id => "startup_maps"
  match "startup_maps" => "startup_maps#index"

  match 'tagged' => 'user_profiles#tagged', :as => 'tagged'

  get "start/index", :id => "start"
  match "start" => "start#index"

  
  resources :business_profiles do
    member do
      post :join
      post :leave
      post :remove
    end
  end

  resources :profile_types

  get "admin/index", :id => "admin"
  match "admin" => "admin#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :user_profiles
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    
    end
    can :edit, UserProfile, :user_id => user.id
    can :edit, BusinessProfile, :owner => user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
  acts_as_gmappable #:check_process => false
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :address, :description, :email, :employees, :facebook, :google, :hiring,
   :image, :name, :phone, :slug, :twitter, :url, :profile_type_ids, :specialty_list, :responsible

  validates_presence_of :description
  validates_uniqueness_of :slug

  has_many :business_profile_types
  has_many :profile_types, :through => :business_profile_types
  has_many :user_business_profiles
  has_many :users, :through => :user_business_profiles

  def gmaps4rails_address
    "#{self.address}" 
  end

  def gmaps4rails_infowindow
    "<a href=\"#{url}\" target=\"_blank\"><h4>#{name}</h4></a>" << "<h4>#{address}</h4>" << "<h4>#{email}</h4>"
  end

  def belongs?(user)
    self.users.first == user.id
  end  

  def find_tag(profile_type_id)
    BusinessProfile.joins(:profile_types).where(:profile_type => {:profile_type_id => profile_type_id})
  end

  default_scope order: 'business_profiles.created_at DESC'

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  attr_accessible :content, :email, :name, :phone, :subject
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :flagged, :title, :url, :votes
end

app/models/profile_type.rb
class ProfileType < ActiveRecord::Base
  attr_accessible :name

  has_many :business_profile_types
  has_many :business_profiles, :through => :business_profile_types

  default_scope order: 'profile_types.name ASC'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged


  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :user_profile_id, :slug, :opt_in

  validates_uniqueness_of :slug
  validates_acceptance_of :accept_terms

  has_one :user_profile, :dependent => :destroy
  has_many :user_business_profiles
  has_many :business_profiles, :through => :user_business_profiles

  def works_here?(business_profile)
    self.business_profiles.include?(business_profile)
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  belongs_to :user

  attr_accessible :about, :email, :facebook, :google, :image, :mentor, :phone, :slug,
   :twitter, :url, :tagline, :linkedin, :github, :skill_list, :interest_list

  validates_presence_of :about, :tagline

  default_scope order: 'user_profiles.created_at DESC'

  def get_user_name
    self.user.try :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_for_mobile
  def index
    @business_profiles = BusinessProfile.limit(5)
    @user_profiles = UserProfile.limit(5)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_for_mobile, :only => [:show]

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    
    @user = User.find(params[:id])
    @user_profile = @user.user_profile
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/startup_maps_helper.rb
module StartupMapsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="span3">
  <h3>My account</h3>
  <p>Username: <%= @user.name %></p>
  <p>Email: <%= @user.email if @user.email %></p>
  <br />
  <% if @user = current_user %>
    <%= link_to 'Change email/password', edit_user_registration_path, :class => "btn btn-info" %>
<% end %>
  <br />
  <hr>
  
</div>

<div class="span5">
  <h2>My profile</h2>
  <% if current_user.user_profile %>
    
    <p><%= image_tag @user_profile.image_url,:class => "profile-pic" if @user_profile.image_url %></p>
    <table class="table">
      <tr>
        <th>About me</th>
        <td><%= @user_profile.about %></td>
      </tr>
      <tr>
        <th>Tagline</th>
        <td><%= @user_profile.tagline %></td>
      </tr>
      <tr>
        <tr>
        <th>Email</th>
        <td><%= @user_profile.email %></td>
      </tr>
      <tr>
        <th>Phone</th>
        <td><%= @user_profile.phone %></td>
      </tr>
      <tr>
        <th>Website</th>
        <td><%= @user_profile.url %></td>
      </tr>
      <tr>
        <th>Twitter</th>
        <td><%= @user_profile.twitter %></td>
      </tr>
      <tr>
        <th>Facebook</th>
        <td><%= @user_profile.facebook %></td>
      </tr>
      <tr>
        <th>Google+</th>
        <td><%= @user_profile.google %></td>
      </tr>
      <tr>
        <th>LinkedIn</th>
        <td><%= @user_profile.linkedin %></td>
      </tr>
      <tr>
        <th>Github</th>
        <td><%= @user_profile.github %></td>
      </tr>

      <tr>

    </table>
     <% if @user = current_user %>
      <%= link_to 'Edit profile', edit_user_profile_path(@user_profile), :class => "btn btn-info" %>
      <%= link_to 'View profile', user_profile_path(current_user.user_profile), :class => "btn btn-info" %>
    <% end %>
  
  <% else %>
    <%= link_to 'Create your profile', new_user_profile_path, :class => "btn btn-success" %>
  <% end %>
  <br><br><br>
</div>
<div class="span4">
  <h3>My business profiles</h3>
  <% if @user.business_profiles.count > 0 %>
     <% @user.business_profiles.each do |business_profile| %>
     <p><b><%= link_to business_profile.name, business_profile_path(business_profile) %></b>
        <% if @user.id == business_profile.owner %> (owner)<% end %>
      </p>
    <% end %>
  <% else %>
    <p><%= link_to "Create a new business profile", new_business_profile_path, :class => "btn btn-success" %></p>
  <% end %>
</div>
</div>