config/routes.rb
Tsc003::Application.routes.draw do
  
  resources :news_items


  get "news/index"

  get "sitemaps/show"

  get "about/index", :id => "about"
  match "about" => "about#index"

  # get "sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
  resources :sitemaps, :only => :show
  match "/sitemap.xml", :controller => "sitemaps", :action => "show", :format => :xml

  resources :contact_forms


  get "terms/index", :id => "terms"
  match "terms" => "terms#index"

  get "privacy/index", :id => "privacy"
  match "privacy" => "privacy#index"

  get "startup_maps/index", :id => "startup_maps"
  match "startup_maps" => "startup_maps#index"

  match 'tagged' => 'user_profiles#tagged', :as => 'tagged'

  get "start/index", :id => "start"
  match "start" => "start#index"

  
  resources :business_profiles do
    member do
      post :join
      post :leave
      post :remove
    end
  end

  resources :profile_types

  get "admin/index", :id => "admin"
  match "admin" => "admin#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :user_profiles
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    
    end
    can :edit, UserProfile, :user_id => user.id
    can :edit, BusinessProfile, :owner => user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/business_profile.rb
class BusinessProfile < ActiveRecord::Base
  acts_as_gmappable #:check_process => false
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :address, :description, :email, :employees, :facebook, :google, :hiring,
   :image, :name, :phone, :slug, :twitter, :url, :profile_type_ids, :specialty_list, :responsible

  validates_presence_of :description
  validates_uniqueness_of :slug

  has_many :business_profile_types
  has_many :profile_types, :through => :business_profile_types
  has_many :user_business_profiles
  has_many :users, :through => :user_business_profiles

  def gmaps4rails_address
    "#{self.address}" 
  end

  def gmaps4rails_infowindow
    "<a href=\"#{url}\" target=\"_blank\"><h4>#{name}</h4></a>" << "<h4>#{address}</h4>" << "<h4>#{email}</h4>"
  end

  def belongs?(user)
    self.users.first == user.id
  end  

  def find_tag(profile_type_id)
    BusinessProfile.joins(:profile_types).where(:profile_type => {:profile_type_id => profile_type_id})
  end

  default_scope order: 'business_profiles.created_at DESC'

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  attr_accessible :content, :email, :name, :phone, :subject
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :flagged, :title, :url, :votes
end

app/models/profile_type.rb
class ProfileType < ActiveRecord::Base
  attr_accessible :name

  has_many :business_profile_types
  has_many :business_profiles, :through => :business_profile_types

  default_scope order: 'profile_types.name ASC'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged


  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :user_profile_id, :slug, :opt_in

  validates_uniqueness_of :slug
  validates_acceptance_of :accept_terms

  has_one :user_profile, :dependent => :destroy
  has_many :user_business_profiles
  has_many :business_profiles, :through => :user_business_profiles

  def works_here?(business_profile)
    self.business_profiles.include?(business_profile)
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  belongs_to :user

  attr_accessible :about, :email, :facebook, :google, :image, :mentor, :phone, :slug,
   :twitter, :url, :tagline, :linkedin, :github, :skill_list, :interest_list

  validates_presence_of :about, :tagline

  default_scope order: 'user_profiles.created_at DESC'

  def get_user_name
    self.user.try :name
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_for_mobile
  def index
    @business_profiles = BusinessProfile.limit(5)
    @user_profiles = UserProfile.limit(5)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/startup_maps_helper.rb
module StartupMapsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

      <!-- Three columns of text below the carousel -->
      <div class="row">
        
        <div class="span6 ">
          <h3><i class="icon-building icon-3x"></i> Recently added startup profiles</h3>
          <table class="table table-condensed">
            <% if @business_profiles.count > 0 %>
            <% @business_profiles.each do |profile| %>
            
              <tr>
                <td><%= image_tag(profile.image_url, :class => "home-pic") %></td>
                <td><strong><%= link_to profile.name, business_profile_path(profile) %></strong></td>
                <td><%= link_to profile.profile_types.first.name, business_profiles_url(:tag => profile.profile_types.first), :class => "btn btn-info btn-fixed-width-2" %></td>
              </tr>
            <% end %>
          <% end %>
          
          </table>



          <div class="pull-right"><%= link_to 'See more', business_profiles_path, :class => "btn btn-primary" %><br><br></div>
          
        </div><!-- /.span4 -->
        <div class="span6 ">
          <h3><i class="icon-group icon-3x"></i> Recently added user profiles</h3>
          <table class="table table-condensed">
            <% if @user_profiles.count > 0 %>
            <% @user_profiles.each do |user_profile| %>
            
              <tr>
                <td><%= image_tag(user_profile.image_url, :class => "home-pic") %></td>
                <td width="25%"><strong><%= link_to user_profile.user.name, user_profile_path(user_profile) %></strong></td>
                <td width="60%"><%= user_profile.tagline[0..60] %><%= link_to '...', user_profile_path(user_profile) %></td>
              </tr>
            <% end %>
          <% end %>
          </table>
          <div class="pull-right"><%= link_to 'See more', user_profiles_path, :class => "btn btn-primary" %><br><br></div>
        </div><!-- /.span4 -->
      </div><!-- /.row -->

app/views/news/index.html.erb
<h1>News#index</h1>
<p>Find me in app/views/news/index.html.erb</p>